name: java
services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
  mongoKongo:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=MongoKongo'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
